"""Integration test against the real proof-of-concept fixture:
resources/p123 (clusters from 1-3-particle events, generated by `sensor`
with `configs/p123.yaml`). Unlike the synthetic unit tests, this data has
genuine pixel-level charge sharing between particles from a common vertex
with a wide opening angle -- some pixels really do have two particles'
charge on top of each other, which is a hard floor on any *pixel-grained*
splitter (truth-based or not): it can pick a dominant owner per pixel, but
it can't do better than the pixel granularity itself.
"""

from pathlib import Path

import pandas as pd
import pytest

from splitting.io import read_run
from splitting.pipeline import apply_splitter
from splitting.truth_splitter import TruthSplitter

RESOURCES = Path(__file__).resolve().parent.parent / "resources" / "p123"
pytestmark = pytest.mark.skipif(not RESOURCES.exists(), reason="resources/p123 fixture not present")


def _dominant_fraction(hits: pd.DataFrame, contributions: pd.DataFrame) -> pd.Series:
    """Per (event_id, cluster_id): the largest single particle's share of
    that cluster's truth-contributed charge (1.0 == perfectly pure)."""
    merged = hits[["event_id", "ix", "iy", "cluster_id"]].merge(
        contributions, on=["event_id", "ix", "iy"], how="inner"
    )
    per_particle = merged.groupby(["event_id", "cluster_id", "particle_id"], as_index=False)["charge"].sum()
    totals = per_particle.groupby(["event_id", "cluster_id"])["charge"].transform("sum")
    return (per_particle["charge"] / totals).groupby(
        [per_particle["event_id"], per_particle["cluster_id"]]
    ).max()


def test_truth_splitter_conserves_hits_and_charge():
    hits, clusters, truth, contributions = read_run(RESOURCES, "arrow")
    new_hits, new_clusters = apply_splitter(TruthSplitter(), hits, clusters, contributions)

    assert len(new_hits) == len(hits)  # splitting only relabels cluster_id, never drops/adds a pixel
    assert new_hits["charge"].sum() == pytest.approx(hits["charge"].sum())
    assert new_clusters["charge_sum"].sum() == pytest.approx(clusters["charge_sum"].sum())
    assert len(new_clusters) >= len(clusters)  # splitting can only create more clusters, never fewer


def test_truth_splitter_improves_purity_but_not_perfectly():
    hits, clusters, truth, contributions = read_run(RESOURCES, "arrow")
    new_hits, new_clusters = apply_splitter(TruthSplitter(), hits, clusters, contributions)

    before = _dominant_fraction(hits, contributions)
    after = _dominant_fraction(new_hits, contributions)

    # on average, splitting meaningfully reduces cross-particle mixing...
    assert after.mean() > before.mean()
    # ...and far more resulting clusters are exactly single-particle...
    assert (after >= 0.999).sum() > (before >= 0.999).sum()
    # ...but genuine pixel-level charge sharing (two tracks from the same
    # vertex landing in the same pixel) means it can't reach perfect purity
    # everywhere -- this dataset has real overlap left even after the best
    # possible per-pixel (oracle/truth) assignment.
    assert (after < 0.999).any()
